hosts:
    - https://bitzlato.com/api

versions:
    - version: <3.0.0
      message: 'Данная версия приложения больше не поддерживается. Вам необходимо обновить приложение'
      blockApp: true

    - version: 3.0.0
      message: 'Вам желательно обновиться'
      blockApp: false

    - version: '>3.0.0'
      message: 'Обновлений нет'
      blockApp: false

app_links:
    android: android_play_market_link
    ios: ios_app_store_link
